//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUTRA
    {
        public string MaTra { get; set; }
        public string MaSach { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PHIEUTRA PHIEUTRA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
