//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTRA()
        {
            this.CHITIETPHIEUTRAs = new HashSet<CHITIETPHIEUTRA>();
        }
    
        public string MaTra { get; set; }
        public string SoThe { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string MaNv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUTRA> CHITIETPHIEUTRAs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THETHUVIEN THETHUVIEN { get; set; }
    }
}
